server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true?characterEncoding=UTF-8
    username: root
    password: root
    hikari:
      pool-name: DayeHikariCP



mybatis-plus:
  mapper-location: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.dxs.pojo
  configuration:
    map-underscore-to-camel-case: false


logging:
  level:
    com.dxs.server.mapper: debug